### PR TITLE
precomp_data.h: add ending newline

### PR DESCRIPTION
**Pull request by vszakats**
some compilers issue a warning if missing.

### CODE REVIEW

**Comment by orlp** [comment]
Hey, I appreciate your effort, but I would prefer it if you would open an issue for trivial changes like this, rather than pull requests.

Since this is a crypto repository, I must take great care while reviewing all pull requests. It would be easier for me to just do the changes yourself, rather than review others' changes.

**Comment by vszakats** [comment]
I'm not sure I understand why explaining so trivial changes is easier than showing it as a two-line diff: https://github.com/orlp/ed25519/pull/6/files
:confused:

**Comment by orlp** [comment]
@vszakats 

Because there are a whole array of things in general that could go wrong, [for example](https://en.wikipedia.org/wiki/IDN_homograph_attack).

**Comment by vszakats** [comment]
Okay, so the issue here is that Watcom C would show warning for each processed source file that is missing a newline at EOF. Files with missing newlines will also show up as warnings here on GitHub (with the hover text "No newline at end of file") and in certain other tools as well.

Here is the diff in plaintext format to clear homograph attack doubts:
https://github.com/vszakats/ed25519/commit/dfddfbaa44292ea066453879bdeff119b80d24ec.diff

**Comment by orlp** [comment]
@vszakats I updated the two files you requested, any other offenders?

**Comment by vszakats** [comment]
Thank you! Yes, found one more that I missed previously:
https://raw.githubusercontent.com/orlp/ed25519/master/src/sha512.h

**Comment by orlp** [comment]
@vszakats Fixed.

**Comment by vszakats** [comment]
Thanks!

**Pull request closed without merging**
